apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: desk-ingress
  namespace: atlas-desk
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - atlas-desk.uaenorth.cloudapp.azure.com
      secretName: desk-tls
  rules:
    - host: atlas-desk.uaenorth.cloudapp.azure.com
      http:
        paths:
          - path: /api/desk/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: desk-api
                port:
                  number: 80
          - path: /hubs/desk(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: desk-signalr
                port:
                  number: 80
