apiVersion: v1
kind: Service
metadata:
  name: desk-api
  namespace: atlas-desk
spec:
  type: ClusterIP
  selector:
    app: desk-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: desk-signalr
  namespace: atlas-desk
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-session-affinity: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: desk-signalr
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
